name: radarr
services:
  radarr:
    container_name: radarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Kolkata
    hostname: radarr
    image: linuxserver/radarr:latest
    ports:
      - target: 7878
        published: "7878"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/radarr/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /media
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Backups/arr/Radarr
        target: /backups
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false