name: twingate-connector
services:
  twingate-connector:
    command:
      - /connectord
    container_name: twingate-esoteric-quetzal
    environment:
      - TWINGATE_NETWORK=
      - TWINGATE_ACCESS_TOKEN=
      - TWINGATE_REFRESH_TOKEN=
      - TWINGATE_LABEL_HOSTNAME=`hostname`
      - TWINGATE_LABEL_DEPLOYED_BY=docker
    hostname: twingate-esoteric-quetzal
    image: twingate/connector:1
    restart: unless-stopped
    sysctls:
      net.ipv4.ping_group_range: 0 2147483647
    networks:
        macvlan:
            ipv4_address: 192.168.3.5
networks:
    macvlan:
        external: true
        name: macvlan