services:
  adguardhome:
    image: adguard/adguardhome:latest

    container_name: adguardhome
    volumes:
      - /DATA/AppData/adguardhome/conf:/opt/adguardhome/conf
      - /DATA/AppData/adguardhome/work:/opt/adguardhome/work
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
            macvlan:
                ipv4_address: 192.168.1.2
          
networks:
    macvlan:
        external: true
        name: macvlan